name: build
on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: .setup.yml

      - name: Build a11y app
        run: npx nx run a11y:build

  e2e:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Setup
        uses: .setup.yml

      - name: Install Cypress Binary
        run: npx cypress install

      - name: Delete previous reports
        run: rm cypress/a11y/junit/* || true

      - name: Test a11y app
        run: npx nx run a11y-e2e:e2e

      - name: Combine junit reports
        run: npx jrm cypress/a11y/combined-junit-report.xml "cypress/a11y/junit/*.xml"

      - name: Publish Test Results in PR
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        if: always()
        with:
          files: |
            cypress/a11y/junit/*.xml
