name: build
on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: senthanal/cplace-playground/.github/workflows/setup.yml@main

      - name: Build a11y app
        run: npx nx run a11y:build

  e2e:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup
        uses: senthanal/cplace-playground/.github/workflows/setup.yml@main
      - name: Test a11y app
        run: npx nx run a11y-e2e:e2e
      - name: Publish Test Results in PR
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            cypress/a11y/index.json
