name: PR
on:
  pull_request:
    branches:
      - '**'

permissions: write-all

jobs:
  install-deps:
    uses: senthanal/cplace-playground/.github/workflows/setup.yml@main

  build:
    needs: install-deps
    uses: senthanal/cplace-playground/.github/workflows/build.yml@main

  e2e:
    needs: install-deps
    uses: senthanal/cplace-playground/.github/workflows/e2e.yml@main
